name: Lint

env:
  SHELLCHECK_OPTS: -e SC1008 -s bash

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run linter
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          additional_files: 'run'
